### ISSUE TITLE
Yo como meserx quiero ver los pedidos que están preparados para entregarlos rápidamente a lxs clientxs que las hicieron.

### ISSUE THREAD

**Issue by ArkellyPerez** [ArkellyPerez/LIM018-burger-queen-api-client#21]

**Comment by ArkellyPerez** [comment]
Criterios de aceptación

- [x] Ver listado de pedido listos para servir.
- [x] Marcar pedidos que han sido entregados.

**Comment by brivanessa** [comment]
- [ ] Ver listado de pedido listos para servir.
- [ ]  Marcar pedidos que han sido entregados.
